apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1> Hi ! The purpose of the project is to output host name of host </h1>
    </br>
    <h1> echo $hostname </h1>
    </html>
